### ISSUE TITLE
Electrical type of pins is `Unspecified`

### ISSUE THREAD

**Issue by simplexion-blechschmidt** [hlord2000/nordic-lib-kicad#13]
Due to all pins on the (e.g. on the nRF9160-SIXX symbol) being `Unspecified`, the ERC is showing a lot of warnings and errors.
NRF provides a [pin assignment table](https://docs.nordicsemi.com/bundle/ps_nrf9160/page/pin.html) that also lists the function.

**Comment by hlord2000** [comment]
Closed by
https://github.com/hlord2000/nordic-lib-kicad/pull/14
