### ISSUE TITLE
nrf9151: Needs a Tag.

### ISSUE THREAD

**Issue by psavary** [hlord2000/nordic-lib-kicad#17]
Hi, Thank you for providing this library, much appreciated.

I wanted to get the new nrf9151 into Kicad, however I think it misses the newest [Tag](https://github.com/hlord2000/nordic-lib-kicad/tags). 
When pulling the info from the[ packages file](https://raw.githubusercontent.com/hlord2000/hlord2000-kicad-repository/main/packages.json), I can only see Tags up until May 23, but I think you merged on [June 4th](https://github.com/hlord2000/nordic-lib-kicad/commit/b5aaf730f64f9f757d117d844277737e08ca178e). 
Could you be so kind and create a new tag so that I can pull the symbol into Kicad? 

Thank you so much!

**Comment by hlord2000** [comment]
Hey @psavary I'm doing a pass through all symbols in preparation for the 54 series. Let me know if you find any issues in symbols and I will tag another version soon.

**Comment by hlord2000** [comment]
New version tagged!
