### ISSUE TITLE
KiCad 7 unable to open file because it was created with a more recent version

### ISSUE THREAD

**Issue by FARLY7** [hlord2000/nordic-lib-kicad#2]
Installed the latest stable release of KiCad 7 (7.0.9), then followed the latest install instructions in the `main` branch. Received this error when loading the library in the schematic editor:

<img width="652" alt="Screenshot 2023-11-18 at 10 16 06" src="https://github.com/hlord2000/nordic-lib-kicad/assets/39262300/f08683f5-0b66-47c1-9c5a-ebac53073fce">

<img width="877" alt="Screenshot 2023-11-18 at 10 17 38" src="https://github.com/hlord2000/nordic-lib-kicad/assets/39262300/0dbe7ff7-b56b-435e-9903-edd84aac578b">

**Comment by FARLY7** [comment]
Installing the latest nightly build worked. I think you should generate the library using the latest _stable_ release, not _nightly_?

**Comment by hlord2000** [comment]
Closed by #5
