### ISSUE TITLE
only bga footprint？

### ISSUE THREAD

**Issue by yangxing844** [hlord2000/nordic-lib-kicad#21]
Hi, first of all, thank you for this  awesome collection! however I don't seem to find other footprint other than bga? the readme says QFN is supported, however I can not find it

**Comment by hlord2000** [comment]
Hello, I'll take a look at this. All of the QFNs use KiCAD standard footprints.

**Comment by hlord2000** [comment]
Refer to KiCAD 8 standard library of footprints
