### ISSUE TITLE
nRF9160-SIXX footprint is missing when README indicates it's included

### ISSUE THREAD

**Issue by FARLY7** [hlord2000/nordic-lib-kicad#3]
<img width="992" alt="Screenshot 2023-11-18 at 16 11 49" src="https://github.com/hlord2000/nordic-lib-kicad/assets/39262300/546bbf70-cc4a-44e9-adea-a7ba93819fe2">

**Comment by FARLY7** [comment]
It seems the footprint is there within the library, it just needs to be manually assigned?

<img width="1392" alt="Screenshot 2023-11-18 at 16 16 35" src="https://github.com/hlord2000/nordic-lib-kicad/assets/39262300/be11c491-9c78-4ab3-8aa7-58b1f4e5b823">

However, after doing so, I get the following error in the board editor:

<img width="782" alt="Screenshot 2023-11-18 at 16 22 12" src="https://github.com/hlord2000/nordic-lib-kicad/assets/39262300/7cfc1357-c57b-45c3-8aa4-e18b73d5cd40">

**Comment by hlord2000** [comment]
Thank you for the issue reports! #2 as well! I will look into this over the next week or so.

**Comment by hlord2000** [comment]
Fixed by #6
