### ISSUE TITLE
Footprint for nRF9161

### ISSUE THREAD

**Issue by Arakistech** [hlord2000/nordic-lib-kicad#4]
Could you please add footprint for nRF9161? It is slightly different from nRF9160.

**Comment by hlord2000** [comment]
Thanks for the issue! The 9161 is not yet available publicly--I cannot add footprints until they are available without NDA.

**Comment by hlord2000** [comment]
Closed w/ https://github.com/hlord2000/nordic-lib-kicad/commit/e9b5a4e1483e48f4504e956a48b8dacd965c80cc
